version: '3'

services:
    laravel.test:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 80:80
            - 5173:5173
        environment:
            WWWUSER: 1000
            XDEBUG_MODE: 'off'
            XDEBUG_CONFIG: client_host=host.docker.internal
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - .:/var/www/html
        depends_on:
            - mariadb

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    mariadb:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: laravel
            MARIADB_DATABASE: laravel
            MARIADB_USER: laravel
            MARIADB_PASSWORD: laravel
        volumes:
            - mariadb:/var/lib/mysql

volumes:
    mariadb:
